### ISSUE TITLE
`--asdeps` option is not respected

### ISSUE THREAD

**Issue by littzhch** [Bekaboo/pacman-install-comments#1]
`pacman -S` has an option `--asdeps`, which is used to manually install a package as dependency. This option is frequently used in AUR helpers like `paru`. However, comments are still required when installing dependencies this way. Is it possible to ignore these `--asdeps` packages and exclude them from `pacman-pkg-comments.log`?

**Comment by Bekaboo** [comment]
I can reproduce this.

`pacman -Qeq` is used in the script to get a list of explicitly installed packages, but I have no idea why packages `pacman -S --asdeps xxx` will be included in the result. PRs welcome to this bug.

**Comment by littzhch** [comment]
I tested again only to find that `-S --asdeps` works just as expected. The problem only occurs when using AUR helpers. `pacman.log` shows that `paru` explicitly installs dependencies and uses `pacman -D --asdeps` to change installation reason later. No wonder the hook can't handle this.

**Comment by littzhch** [comment]
I'll close this issue and open a new one since `--asdeps` does work.
